export const LOAD_GIFS_SUCCESS = 'LOAD_GIFS_SUCCESS';
export const LOAD_GIFS_INPROGRESS = 'LOAD_GIFS_INPROGRESS';
export const LOAD_GIFS_LAZYLOADING_INPROGRESS = 'LOAD_GIFS_LAZYLOADING_INPROGRESS';
export const LOAD_SEARCH_SUGGESTIONS_SUCCESS = 'LOAD_SEARCH_SUGGESTIONS_SUCCESS';